### PR TITLE
Suggest `go fmt` changes instead of commiting to PR

### LINKED ISSUE #43: adjust `Go / fmt (pull_request)` check
Firstly, the check auto-formats and auto-commits changes to branches. This is behavior I tend to not like. We should modify the check to only check that the code is formatted. It should not auto-commit any changes.

Secondly, it seems to fail when run on a PR for branches on other remotes. For example, see this [run][1].

[1]: https://github.com/nishanths/license/actions/runs/3230131715/jobs/5290280909

### PR DESCRIPTION
**Pull request by norwd**
Run `go fmt -x` on pull requests, but only suggest theme instead of committing directly to the PR.

Closes #43

### CODE REVIEW

**Comment by norwd** [comment]
Instead of commiting the changes directly, this workflow now makes comments on the PR itself and suggests adding the changes. Allowing maintainers to opt-in to formatting changes.

image

Changes can be cherry-picked, or committed in batches through the GitHub UI.

image

See example: https://github.com/norwd/pword/pull/29/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261

**Comment by nishanths** [comment]
Thank you. This is much better than the check we have in master. But it may add a lot of formatting-related review comments, which isn't the main focus in a code review. 

I feel we should do something like the following for this step. 

```sh
run: |
  out="$(gofmt -d . )"
  if [ -n "$out" ]; then
      echo "$out" && exit 1
  fi
```

It runs `gofmt`. If a diff is produced (i.e. formatting on the branch differs from gofmt), then it prints the diff and exits with an error.

**Comment by nishanths** [comment]
I made this pull request based on my comment above: https://github.com/nishanths/license/pull/46.

**Comment by nishanths** [comment]
Thank you for the change. But I will close this PR and use the other one.

**Pull request closed without merging**
